# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=200)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date sent')),
            ],
        ),
    ]
