# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('username', models.CharField(max_length=300)),
                ('is_chat_user', models.BooleanField(default=False)),
                ('gravatar_url', models.CharField(max_length=300)),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gravatar', models.CharField(max_length=300)),
            ],
        ),
    ]
