# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
