# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='current_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoroom',
            name='started_playing',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='started playing'),
        ),
    ]
