# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoroom',
            name='status',
        ),
        migrations.AddField(
            model_name='videoroom',
            name='paused',
            field=models.BooleanField(default=True),
        ),
    ]
