# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/placeholder.jpg', upload_to=user.models.avatar_directory_path),
        ),
    ]
