# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161029_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
