# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='rejected',
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
